### 책등록
POST http://localhost:8085/api/v1/book
Content-Type: application/json

{
  "title": "제목1",
  "author": "12314"
}

###책목록보기
GET http://localhost:8085/api/v1/book

###책 한건보기
GET http://localhost:8085/api/v1/book/1

###책 삭제
DELETE http://localhost:8085/api/v1/book/1